debug = false

logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
[api]
entryPoint = "traefik"
dashboard = true
debug = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "emedika.id"
exposedByDefault = false
watch = true
network = "web"

[acme]
entryPoint = "https"
email = "franatagola@gmail.com"
storage = "acme.json"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

[file]
watch = true

